services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_URL=postgres://panel:password@database:5432/minepanel
      - LISTEN_ADDRESS=:8080
    depends_on:
      - database
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=panel
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=minepanel